display_groups: Kategorie_plateb # categorization column
counterparty: counterparty # columns to do categorization on, protistrana is generated as concat of protistrana ids
message: message  # concat of protistrana_ids cols
amount: částka
date:
  col: datum # standardized name for date
  format:
    - '%Y-%m-%d'
generated_suggestions: category_suggestion
transaction_type: Typ transakce
payment_category: Kategorie_plateb # standardized name for category
sort_by:
  - Kategorie_plateb
  - měsíc # processed columns